# Generated by Django 3.2.2 on 2021-05-08 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_types', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Sony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carmodels', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polimorfismapp.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Pioneer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carmodels', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polimorfismapp.carmodel')),
            ],
        ),
    ]
